adverts_index:
    path:     /
    defaults: { _controller: "DefaultBundle:Adverts:index" }
    methods:  GET

adverts_show:
    path:     /{id}/show
    defaults: { _controller: "DefaultBundle:Adverts:show" }
    methods:  GET

adverts_new:
    path:     /new
    defaults: { _controller: "DefaultBundle:Adverts:new" }
    methods:  [GET, POST]

adverts_edit:
    path:     /{id}/edit
    defaults: { _controller: "DefaultBundle:Adverts:edit" }
    methods:  [GET, POST]

adverts_filter1:
    path:     /Suvorovskiy
    defaults: { _controller: "DefaultBundle:Adverts:filter1" }

adverts_filter2:
    path:     /Kominternovskiy
    defaults: { _controller: "DefaultBundle:Adverts:filter2" }

adverts_filter3:
    path:     /Malinovskiy
    defaults: { _controller: "DefaultBundle:Adverts:filter3" }

adverts_filter4:
    path:     /Primorskiy
    defaults: { _controller: "DefaultBundle:Adverts:filter4" }

adverts_filter5:
    path:     /Kievskiy
    defaults: { _controller: "DefaultBundle:Adverts:filter5" }

adverts_delete:
    path:     /{id}/delete
    defaults: { _controller: "DefaultBundle:Adverts:delete" }
    methods:  DELETE
