auctionbet_index:
    path:     /
    defaults: { _controller: "DefaultBundle:AuctionBet:index" }
    methods:  GET

auctionbet_show:
    path:     /{id}/show
    defaults: { _controller: "DefaultBundle:AuctionBet:show" }
    methods:  GET

auctionbet_new:
    path:     /new
    defaults: { _controller: "DefaultBundle:AuctionBet:new" }
    methods:  [GET, POST]

auctionbet_edit:
    path:     /{id}/edit
    defaults: { _controller: "DefaultBundle:AuctionBet:edit" }
    methods:  [GET, POST]

auctionbet_delete:
    path:     /{id}/delete
    defaults: { _controller: "DefaultBundle:AuctionBet:delete" }
    methods:  DELETE
