commentstoadvert_index:
    path:     /{idAdvert}/list
    defaults: { _controller: "DefaultBundle:CommentsToAdvert:index" }
    methods:  GET
    requirements:
        idAdvert: \d+

commentstoadvert_show:
    path:     /{id}/show
    defaults: { _controller: "DefaultBundle:CommentsToAdvert:show" }
    methods:  GET

commentstoadvert_new:
    path:     /new/{idAdvert}
    defaults: { _controller: "DefaultBundle:CommentsToAdvert:new" }
    methods:  [GET, POST]
    requirements:
        idAdvert: \d+

commentstoadvert_edit:
    path:     /{id}/edit
    defaults: { _controller: "DefaultBundle:CommentsToAdvert:edit" }
    methods:  [GET, POST]

commentstoadvert_delete:
    path:     /{id}/delete
    defaults: { _controller: "DefaultBundle:CommentsToAdvert:delete" }
    methods:  DELETE
