commentphoto_index:
    path:     /
    defaults: { _controller: "DefaultBundle:CommentPhoto:index" }
    methods:  GET

commentphoto_show:
    path:     /{id}/show
    defaults: { _controller: "DefaultBundle:CommentPhoto:show" }
    methods:  GET

commentphoto_new:
    path:     /new
    defaults: { _controller: "DefaultBundle:CommentPhoto:new" }
    methods:  [GET, POST]

commentphoto_edit:
    path:     /{id}/edit
    defaults: { _controller: "DefaultBundle:CommentPhoto:edit" }
    methods:  [GET, POST]

commentphoto_delete:
    path:     /{id}/delete
    defaults: { _controller: "DefaultBundle:CommentPhoto:delete" }
    methods:  DELETE
