commentstouser_index:
    path:     /{idUser}/list
    defaults: { _controller: "DefaultBundle:CommentsToUsers:index" }
    methods:  GET
    requirements:
        idUser: \d+

commentstouser_show:
    path:     /{id}/show
    defaults: { _controller: "DefaultBundle:CommentsToUsers:show" }
    methods:  GET

commentstouser_new:
    path:     /new/{idUser}
    defaults: { _controller: "DefaultBundle:CommentsToUsers:new" }
    methods:  [GET, POST]
    requirements:
        idUser: \d+

commentstouser_edit:
    path:     /{id}/edit
    defaults: { _controller: "DefaultBundle:CommentsToUsers:edit" }
    methods:  [GET, POST]

commentstouser_delete:
    path:     /{id}/delete
    defaults: { _controller: "DefaultBundle:CommentsToUsers:delete" }
    methods:  DELETE
