users_index:
    path:     /
    defaults: { _controller: "DefaultBundle:Users:index" }
    methods:  GET

users_show:
    path:     /{id}/show
    defaults: { _controller: "DefaultBundle:Users:show" }
    methods:  GET

users_new:
    path:     /new
    defaults: { _controller: "DefaultBundle:Users:new" }
    methods:  [GET, POST]

users_edit:
    path:     /{id}/edit
    defaults: { _controller: "DefaultBundle:Users:edit" }
    methods:  [GET, POST]

users_delete:
    path:     /{id}/delete
    defaults: { _controller: "DefaultBundle:Users:delete" }
    methods:  DELETE

users_login:
    path: /login
    defaults: {_controller: "DefaultBundle:Users:login" }

users_confirm_email:
    path: /email/confirm/{id}
    defaults: {_controller: "DefaultBundle:Users:confirmUser" }
    methods: GET
    requirements:
           id: \d+
