app:
    resource: '@DefaultBundle/Controller/'
    type: annotation

default_adverts:
    resource: "@DefaultBundle/Resources/config/routing/adverts.yml"
    prefix:   /adverts

default_commentstoadvert:
    resource: "@DefaultBundle/Resources/config/routing/commentstoadvert.yml"
    prefix:   /commentstoadvert

default_report:
    resource: "@DefaultBundle/Resources/config/routing/report.yml"
    prefix:   /report

default_users:
    resource: "@DefaultBundle/Resources/config/routing/users.yml"
    prefix:   /users

default_message:
    resource: "@DefaultBundle/Resources/config/routing/message.yml"
    prefix:   /message

default_commentstouser:
    resource: "@DefaultBundle/Resources/config/routing/commentstouser.yml"
    prefix:   /commentstouser

logout:
    path: /exit

default_basket:
    resource: "@DefaultBundle/Resources/config/routing/basket.yml"
    prefix:   /basket

default_advertphoto:
    resource: "@DefaultBundle/Resources/config/routing/advertphoto.yml"
    prefix:   /advertphoto






