default_adverts:
    resource: "@DefaultBundle/Resources/config/routing/adverts.yml"
    prefix:   /adverts

default_media:
    resource: "@DefaultBundle/Resources/config/routing/media.yml"
    prefix:   /media

default_commentstoadvert:
    resource: "@DefaultBundle/Resources/config/routing/commentstoadvert.yml"
    prefix:   /commentstoadvert

default_report:
    resource: "@DefaultBundle/Resources/config/routing/report.yml"
    prefix:   /report

default_users:
    resource: "@DefaultBundle/Resources/config/routing/users.yml"
    prefix:   /users

default_commentstouser:
    resource: "@DefaultBundle/Resources/config/routing/commentstouser.yml"
    prefix:   /commentstouser

default_basket:
    resource: "@DefaultBundle/Resources/config/routing/basket.yml"
    prefix:   /basket

default_message:
    resource: "@DefaultBundle/Resources/config/routing/message.yml"
    prefix:   /message

default_advertphoto:
    resource: "@DefaultBundle/Resources/config/routing/advertphoto.yml"
    prefix: /advertphoto









