services:
#    default.example:
#        class: DefaultBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

  myshop_admin.sending_mail:
         class: DefaultBundle\Services\MailNotification
         arguments:
             - "@mailer"
  api.json_serializer:
         class: DefaultBundle\API\JSONSerializer