<?php
namespace DefaultBundle\Repository;
/**
 * AdvertPhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertPhotoRepository extends \Doctrine\ORM\EntityRepository
{
}