<?php

namespace DefaultBundle\Repository;

/**
 * AuctionBetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuctionBetRepository extends \Doctrine\ORM\EntityRepository
{
}
