<?php

namespace DefaultBundle\Repository;

/**
 * CommentsToAdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsToAdvertRepository extends \Doctrine\ORM\EntityRepository
{
}
