<?php

namespace DefaultBundle\Repository;

/**
 * CommentsToRenterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsToRenterRepository extends \Doctrine\ORM\EntityRepository
{
}
