<?php

namespace DefaultBundle\Repository;

/**
 * CommentsToUsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsToUsersRepository extends \Doctrine\ORM\EntityRepository
{
}
