<?php

namespace DefaultBundle\Repository;

/**
 * OrderAdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderAdvertRepository extends \Doctrine\ORM\EntityRepository
{
}
