<?php

namespace DefaultBundle\Repository;

/**
 * ReadyBetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReadyBetRepository extends \Doctrine\ORM\EntityRepository
{
}
