<?php

namespace DefaultBundle\Repository;

/**
 * RentersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RentersRepository extends \Doctrine\ORM\EntityRepository
{
}
