<?php

namespace DefaultBundle\Repository;

use DefaultBundle\Entity\UserOrder;
use DefaultBundle\Entity\Users;

/**
 *UserOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserOrderRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOrCreateOrder(Users $user)
    {
        $manager = $this->getEntityManager();


        $dql = 'select o from DefaultBundle:UserOrder o where o.user = :userName and o.status = :status ';

        $order = $manager->createQuery($dql)->setParameters([
            'userName' => $user,
            'status' => UserOrder::STATUS_OPEN
        ])->getOneOrNullResult();

        if($order == null){
            $order = new UserOrder();
            $user->addOrder($order);
            $manager->persist($user);
            $manager->flush();
        }

        return $order;
    }
}
